src/urban/chat/urls.py
from django.conf.urls import url
from urban.chat import views

urlpatterns = [
    url(r'^admin/$', views.admin_chat, name="admin"),
    url(r'^getHistory/$', views.get_history, name="join"),
    url(r'^join/$', views.join, name="join"),
    url(r'^send/$', views.send, name="send"),
]

src/urban/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

from urban import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^$', views.index, name="index"),
    url(r'^(?P<lang_code>[a-z]+)/$', views.index, name="index"),
    url(r'^services/(?P<slug>[A-z0-9_\-.]+)/$', views.services, name="services"),
    url(r'^(?P<lang_code>[a-z]+)/services/(?P<slug>[A-z0-9_\-.]+)/$', views.services, name="services"),
    url(r'^chat/', include('urban.chat.urls', namespace="chat")),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]


if settings.DEBUG:
    urlpatterns += [
        url(r'^layout/(?P<template>[A-z0-9_\-.]+)/$', views.layout),
    ]

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/urban/chat/models.py
from django.contrib.auth.models import User
from django.db import models


class Dialog(models.Model):
    owner = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    admin = models.ForeignKey(User, related_name="admin", null=True)


class Message(models.Model):
    from_user = models.ForeignKey(User, related_name="from_user")
    to_user = models.ForeignKey(User, related_name="to_user")
    text = models.TextField()
    datetime = models.DateTimeField()

src/urban/chat/views.py
from django.shortcuts import render_to_response
from django.template.loader import render_to_string
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response

from urban.chat.serializers import JoinSerializer
from urban.views import main_context


def admin_chat(request):

    context = main_context(request)
    return render_to_response("admin_chat.html", context=context)


@api_view(["POST"])
def join(request):
    serializer = JoinSerializer(request.data)
    if not serializer.is_valid():
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    if not request.session.exists(request.session.session_key):
        request.session.create()

    serializer.save(owner=request.session.session_key)
    return Response(status=status.HTTP_200_OK)


@api_view(["POST"])
def send(request):
    return Response(status=status.HTTP_200_OK)


@api_view(["GET"])
def get_history(request):
    data = {
        "needJoin": True,
        "joinForm": render_to_string("chat/greet_form.html"),
    }
    return Response(data, status=status.HTTP_200_OK)

src/frontend/templates/chat/greet_form.html
<div class="greet_form">
    <div class="in">
        <div class="triangle"></div>
        <div class="text">
            Здравствуйте! У вас появились вопросы? Возможно, вашу проблему можно решить онлайн!
            Заполните форму ниже, Вам ответит первый освободившийся оператор.
        </div>
    </div>

    <div class="form">
        <form action="{% url "chat:join" %}" id="chat-join-form">
            <div class="form-row">
                <input placeholder="Имя" type="text" name="name">
            </div>
            <div class="form-row">
                <textarea placeholder="Введите сообщение" name="text" rows=2></textarea>
            </div>
            <input type="submit" value="Отправить">
        </form>
    </div>
</div>

src/frontend/templates/chat/message.html
<div class="{{ src }}">
    <div class="triangle"></div>
    <div class="text">
        {{ message }}
    </div>
    <div class="time">{{ time }}</div>
</div>