src/urban/chat/urls.py
from django.conf.urls import url
from urban.chat import views

urlpatterns = [
    url(r'^admin/$', views.admin_chat, name="admin"),
    url(r'^getHistory/$', views.get_history, name="join"),
    url(r'^join/$', views.join, name="join"),
    url(r'^send/$', views.send, name="send"),
]

src/urban/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

from urban import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^$', views.index, name="index"),
    url(r'^(?P<lang_code>[a-z]+)/$', views.index, name="index"),
    url(r'^services/(?P<slug>[A-z0-9_\-.]+)/$', views.services, name="services"),
    url(r'^(?P<lang_code>[a-z]+)/services/(?P<slug>[A-z0-9_\-.]+)/$', views.services, name="services"),
    url(r'^chat/', include('urban.chat.urls', namespace="chat")),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]


if settings.DEBUG:
    urlpatterns += [
        url(r'^layout/(?P<template>[A-z0-9_\-.]+)/$', views.layout),
    ]

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/urban/chat/models.py
from django.contrib.auth.models import User
from django.db import models


class Dialog(models.Model):
    owner = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    admin = models.ForeignKey(User, related_name="admin", null=True)


class Message(models.Model):
    from_user = models.ForeignKey(User, related_name="from_user")
    to_user = models.ForeignKey(User, related_name="to_user")
    text = models.TextField()
    datetime = models.DateTimeField()

src/urban/services/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from django.urls import reverse

from tinymce.forms import TinyMCEField
from urban.preferences.models import Language, LanguageModelManager
from django.utils.translation import ugettext as _


class Category(models.Model):
    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

    slug = models.CharField(max_length=60)
    objects = LanguageModelManager("category")

    def translation(self):
        return self.translations.all().filter(language=Language.current).first()

    def permalink(self):
        if Language.current.country_code == "ru":
            return reverse("services", kwargs={"slug": self.slug})

        return reverse("services", kwargs={"slug": self.slug, "lang_code": Language.current.country_code})

    def __str__(self):
        tset = self.translations.all()
        translation = tset.filter(language__country_code="ru").first()
        translation = translation or tset.first()

        if translation is not None:
            return translation.name
        else:
            return self.pk


class CategoryTranslation(models.Model):
    class Meta:
        default_related_name = "translations"

    category = models.ForeignKey(Category)
    language = models.ForeignKey(Language, verbose_name="Язык", related_name="service_category_lang",
                                 null=True, blank=True)

    name = models.CharField(max_length=60)


class Service(models.Model):
    class Meta:
        verbose_name = _("Услуга")
        verbose_name_plural = "Услуги"

    category = models.ForeignKey(Category)
    is_popular = models.BooleanField(default=False)

    objects = LanguageModelManager("service")

    def translation(self):
        return self.translations.all().filter(language=Language.current).first()

    def __str__(self):
        tset = self.translations.all()
        translation = tset.filter(language__country_code="ru").first()
        translation = translation or tset.first()

        if translation is not None:
            return translation.name
        else:
            return self.pk


class ServiceTranslation(models.Model):
    class Meta:
        default_related_name = "translations"

    service = models.ForeignKey(Service)
    language = models.ForeignKey(Language, verbose_name="Язык",
                                 related_name="service_lang", null=True, blank=True)

    name = models.CharField(max_length=60)
    price = models.CharField(max_length=20)
    details = RichTextUploadingField(default="<p>No details</p>")

src/urban/chat/views.py
from django.shortcuts import render_to_response
from django.template.loader import render_to_string
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response

from urban.chat.serializers import JoinSerializer
from urban.views import main_context


def admin_chat(request):

    context = main_context(request)
    return render_to_response("admin_chat.html", context=context)


@api_view(["POST"])
def join(request):
    serializer = JoinSerializer(request.data)
    if not serializer.is_valid():
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    if not request.session.exists(request.session.session_key):
        request.session.create()

    serializer.save(owner=request.session.session_key)
    return Response(status=status.HTTP_200_OK)


@api_view(["POST"])
def send(request):
    return Response(status=status.HTTP_200_OK)


@api_view(["GET"])
def get_history(request):
    data = {
        "needJoin": True,
        "joinForm": render_to_string("chat/greet_form.html"),
    }
    return Response(data, status=status.HTTP_200_OK)

src/urban/services/views.py
from django.shortcuts import render

# Create your views here.

src/frontend/templates/admin_chat.html
<div class="dialogs">
    <div class="header">
        Диалоги с посетителями
    </div>

    <div class="dialog">
        <a href="#" class="close">Закрыть чат [x]</a>
        <div class="name">Юлия Пивоварова</div>
        <div class="last-message">Добрый день</div>
    </div>

    <div class="dialog">
        <a href="#" class="close">Закрыть чат [x]</a>
        <div class="name">Антон Андреев</div>
        <div class="last-message"><span class="highlight">Вы:</span> Сейчас посмотрю</div>
    </div>

    <div class="dialog">
        <a href="#" class="close">Закрыть чат [x]</a>
        <div class="name">Сергей 45k</div>
        <div class="last-message">Здравствуйте, у меня вопрос</div>
    </div>
</div>

<div class="messages">
    <div class="header">
        <a href="#" class="icon close"></a>
    </div>

    <div class="messages">
        <div class="in">
            <div class="triangle"></div>
            <div class="text">
                Привет
            </div>
            <div class="time">12:16</div>
        </div>

        <div class="out">
            <div class="triangle"></div>
            <div class="text">
                Здравствуйте, чем могу помочь?
            </div>
            <div class="time">12:17</div>
        </div>

        <div class="in">
            <div class="triangle"></div>
            <div class="text">
                Не работает компьютер
            </div>
            <div class="time">12:17</div>
        </div>

        <div class="out">
            <div class="triangle"></div>
            <div class="text">
                Вам выставлен счет

                <div class="pay">
                    <div class="price">20 $</div>
                    <a href="#" class="button">Оплатить</a>
                    <div class="cards">
                        <div class="visa"></div>
                        <div class="maestro"></div>
                    </div>
                </div>
            </div>
            <div class="time">12:17</div>
        </div>
    </div>

    <div class="send-form">
        <div class="message">
            <form action="{% url "chat:send" %}">
                <textarea placeholder="Напишите сообщение и нажмите Enter"></textarea>
                <input type="submit">
            </form>
        </div>

        <div class="attachment">
            <div class="download-region">
                <span class="note">
                    Перетаците файл или <span class="highlight">загрузите с компьютера</span>
                </span>
            </div>
        </div>

        <div class="order">
            <input type="text" placeholder="Введите сумму">
            <ul class="currency">
                <li data-currency="rub">RUB</li>
                <li data-currency="usd">USD</li>
                <li data-currency="eur">EUR</li>
                <li data-currency="pln">PLN</li>
            </ul>
        </div>

        <div class="bottom-menu">
            <a href="#" data-tab="message"><div class="icon messages"></div></a>
            <a href="#" data-tab="attachment"><div class="icon attachment"></div></a>
            <a href="#" data-tab="order"><div class="icon dollar"></div></a>
        </div>
    </div>
</div>

src/frontend/templates/base.html
{% load staticfiles %}
{% load compress %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% trans "Urban" %} - {% endblock %}</title>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed&subset=cyrillic" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto&subset=cyrillic" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Exo+2:400,600,500,700&subset=latin,cyrillic' rel='stylesheet' type='text/css'>

    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    {% compress css %}
        {% block styles %}
            <link href="{% static "vendor/font-awesome.min.css" %}" rel="stylesheet" type="text/css">
            <link href="{% static "fonts/OCR_OneCTT.css" %}" rel="stylesheet" type="text/css">
            <link href="{% static "styles/main.sass" %}" rel="stylesheet" type="text/x-sass">
{#            <link href="{% static "styles/break.css" %}" rel="stylesheet">#}
            <link rel="stylesheet" type="text/css" href="{% static "vendor/jquery.fullpage.min.css" %}" />
            <link rel="stylesheet" type="text/css" href="{% static "vendor/slick.css" %}"/>
        {% endblock %}
    {% endcompress %}
</head>
<body>
    {% include "header.html" %}

    {% block content %}
    {% endblock %}

    {% block js %}
        <!-- {literal} -->
        <script type='text/javascript'>
            window['li' + 've' + 'Tex'] = true,
                window['liv' + 'eT' + 'exI' + 'D'] = 142609,
                window['liveTe' + 'x_objec' + 't'] = true;
            (function () {
                var t = document['c' + 'rea' + 'te' + 'Ele' + 'ment']('script');
                t.type = 'text/javascript';
                t.async = true;
                t.src = '//cs15.' + 'livete' + 'x.' + 'ru/js/cl' + 'ient' + '.js';
                var c = document['getEle' + 'mentsByTag' + 'Nam' + 'e']('script')[0];
                if (c) c['pa' + 'r' + 'en' + 't' + 'N' + 'od' + 'e']['inser' + 'tB' + 'ef' + 'ore'](t, c);
                else document['doc' + 'u' + 'm' + 'entE' + 'le' + 'm' + 'e' + 'nt']['fi' + 'rst' + 'C' + 'hild']['a' + 'ppe' + 'ndCh' + 'ild'](t);
            })();
        </script>
        <!-- {/literal} -->

        <script src="{% static 'vendor/jquery-3.1.1.min.js' %}" charset="utf-8"></script>
        <script src="{% static 'vendor/jquery.fullpage.min.js' %}" charset="utf-8"></script>
        <script src="{% static 'vendor/slick.min.js' %}" charset="utf-8"></script>
        <script src="{% static 'js/main.js' %}" charset="utf-8"></script>
{#        <script src="{% static 'js/chat.js' %}" charset="utf-8"></script>#}
    {% endblock %}
</body>
</html>

src/frontend/templates/chat.html
<div id="online-chat">
    <div class="border-header">
        <a href="#" class="icon close"></a>
    </div>

    <div class="toolbar">
        <div class="icon-place">
            <div class="icon messages-white"></div>
        </div>

        <div class="header">Консультация on-line</div>

        <div class="menu-button">
            <div class="icon hamburger"></div>
        </div>
    </div>

    <div class="info-messages">
    </div>

    <ul class="toolbar-menu">
        <li><div class="icon email"></div> <div class="text">Отправить на e-mail</div><div class="clearfix"></div></li>
        <li><div class="icon team-viewer"></div> <div class="text">Team Viewer</div><div class="clearfix"></div></li>
        <li><div class="icon ammyy-admin"></div> <div class="text">Ammyy Admin</div><div class="clearfix"></div></li>
        <li><div class="icon chrome-remote-desktop"></div> <div class="text">Chrome Remote Desktop</div><div class="clearfix"></div></li>
        <li class="last"><div class="icon print"></div> <div class="text">Распечатать переписку</div><div class="clearfix"></div></li>
    </ul>

    <div class="messages">
{#        <div class="in">#}
{#            <div class="triangle"></div>#}
{#            <div class="text">#}
{#                Добрый день#}
{#            </div>#}
{#            <div class="time">12:36</div>#}
{#        </div>#}
{##}
{#        <div class="out">#}
{#            <div class="triangle"></div>#}
{#            <div class="text">#}
{#                Здравствуйте. У меня не получается запустить Chrome. Всё перепробовал. Можете помочь,#}
{#            </div>#}
{#            <div class="time">12:37</div>#}
{#        </div>#}
{##}
{#        <div class="dialog-finished">#}
{#            <div class="finished-text">Консультат закрыл чат.</div>#}
{#            <div class="rate">Оценка чата: <a class="fa fa-thumbs-up"></a> <a class="fa fa-thumbs-down"></a></div>#}
{#        </div>#}
{#    </div>#}
{##}
{#    <div class="send-form">#}
{#        <div class="message">#}
{#            <form action="{% url "chat:send" %}">#}
{#                <textarea placeholder="Напишите сообщение и нажмите Enter"></textarea>#}
{#                <input type="submit">#}
{#            </form>#}
{#        </div>#}
{##}
{#        <div class="attachment">#}
{#            <div class="download-region">#}
{#                <span class="note">#}
{#                    Перетаците файл или <span class="highlight">загрузите с компьютера</span>#}
{#                </span>#}
{#            </div>#}
{#        </div>#}
{##}
{#        <div class="bottom-menu">#}
{#            <a href="#" data-tab="message"><div class="icon messages"></div></a>#}
{#            <a href="#" data-tab="attachment"><div class="icon attachment"></div></a>#}
{#        </div>#}
    </div>
</div>

src/frontend/templates/header.html
{% load i18n %}

<div class="menu">
    <ul>
        <li><a href="{% url "index" %}">{% trans "Главная страница" %}</a></li>
        {% for category in categories %}
            <li><a href="{{ category.permalink }}">{{ category.translation.name }}</a></li>
        {% endfor %}
    </ul>
    <div class="tel">
        <div>{% trans "Вызов мастера" %}</div>
        <div class="number">{{ preferences.translation.master_phone }}</div>
    </div>
</div>

<a href="#" id="mobile-menu-link"><i class="fa fa-bars"></i></a>

<div id="mobile-menu">
    <a href="#" id="mobile-menu-close"><i class="fa fa-times-thin"></i></a>

    <ul>
        <li><a href="{% url "index" %}">{% trans "Главная страница" %}</a></li>

        {% for category in categories %}
            <li><a href="{{ category.permalink }}">{{ category.translation.name }}</a></li>
        {% endfor %}
    </ul>

    <div class="mobile-languages">
        {% for language in languages %}
            <a href="{{ language.permalink }}" {% if language.active %}class="active"{% endif %}>
                {{ language.country_code }}
            </a>

            {% if not forloop.last %}
                <div class="separator"></div>
            {% endif %}
        {% endfor %}
        <div class="clearfix"></div>
    </div>

    <div class="mobile-socials">
        <a href="{{ preferences.vk_url }}" target="_blank" class="vk"></a>
        <a href="{{ preferences.fb_url }}" target="_blank" class="fb"></a>
        <a href="{{ preferences.tw_url }}" target="_blank" class="tw"></a>
        <div class="clearfix"></div>
    </div>
</div>

<div class="languages">
    {% for language in languages %}
        <a href="{{ language.permalink }}"{% if language.active %} class="active"{% endif %}>{{ language.country_code }}</a>
        {% if not forloop.last %}
            <div class="separator"></div>
        {% endif %}
    {% endfor %}
</div>

<div class="socials">
    <a href="{{ preferences.vk_url }}" target="_blank" class="vk"></a>
    <a href="{{ preferences.fb_url }}" target="_blank" class="fb"></a>
    <a href="{{ preferences.tw_url }}" target="_blank" class="tw"></a>
</div>

<div class="contact-text">
    {% blocktrans %}Свяжитесь с нами и мы ответим на все интересующие Вас вопросы. Звоните: {{ preferences.translation.info_phone }} или
    оставьте <a href="#" class="open-modal" data-modal="contact-modal">on-line</a> заявку.{% endblocktrans %}
</div>

<div class="modal" id="contact-modal">
    <div class="wrapper">
        <a href="#" class="close"></a>
        <h1>{% trans "Оставить заявку" %}</h1>
        <form method="post" action="">
            {% csrf_token %}
            {% for field in contact_form %}
                {{ field }}
            {% endfor %}
            <input type="submit" value="{% trans "Оставить заявку" %}">
        </form>
    </div>
</div>

{% if contact_form_fail %}
    <div class="modal" style="display: block; opacity: 1;">
        <div class="wrapper">
            <a href="#" class="close"></a>
            <h2>{% trans "Что-то пошло не так, пожалуйста напишити нам на email:" %}
                <a href="mailto:{{ preferences.send_email }}">{{ preferences.send_email }}</a>
            </h2>
        </div>
    </div>
{% elif contact_form_success %}
    <div class="modal" style="display: block; opacity: 1;">
        <div class="wrapper">
            <a href="#" class="close"></a>
            <h2>{% trans "Сообщение успешно отправлено, мы с вами свяжемся в ближайшее время." %}</h2>
        </div>
    </div>
{% endif %}

src/frontend/templates/index.html
{% extends 'base.html' %}

{% load staticfiles %}
{% load i18n %}

{% block title %}
    {{ block.super }}
    {% trans "Главная страница" %}
{% endblock %}

{% block styles %}
    {{ block.super }}
    <link href="{% static "styles/chat.sass" %}" rel="stylesheet" type="text/x-sass">
{% endblock %}

{% block content %}
    <div id="fullpage">
        {% include "index_page/title_section.html" %}
        {% include "index_page/reviews_section.html" %}
        {% include "index_page/footer_section.html" %}
    </div>

{#    {% include "chat.html" %}#}
{% endblock %}

src/frontend/templates/services.html
{% extends 'base.html' %}

{% load staticfiles %}
{% load i18n %}

{% block title %}
    {{ block.super }}
    {{ category.translation.name }}
{% endblock %}

{% block styles %}
    {{ block.super }}
    <link href="{% static "styles/chat.sass" %}" rel="stylesheet" type="text/x-sass">
{% endblock %}

{% block content %}
    <div id="fullpage" class="services">
        <div class="section" id="regular">
            <div class="overlay"></div>
            <div class="row auto-height">
                <div class="left">
                    <h1>{{ category.translation.name }}</h1>
                    <div class="contacts">
                        <h2>{% trans "Вызов мастера и консультация" %}</h2>
                        <div class="tel">{{ preferences.translation.master_phone }}</div>
                        <button class="open-modal" data-modal="contact-modal">{% trans "Оставить заявку" %}</button>
                    </div>
                </div>

                <div class="right">
                    <div class="wrapper">
                        {% for service in services %}
                            <a href="#" class="open-modal" data-modal="service-details-{{ service.id }}">
                                {{ service.translation.name }}
                                <div class="price">{{ service.translation.price }}</div>
                            </a>
                        {% endfor %}
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{#    {% include "chat.html" %}#}
    {% for service in services %}
        <div class="modal" id="service-details-{{ service.id }}">
            <div class="wrapper">
                <a href="#" class="close"></a>
                <h1>{{ service.translation.name }}</h1>
                <div>
                    {{ service.translation.details|safe }}
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}